#!/bin/bash

#SBATCH --ntasks=40
#SBATCH --nodes=1
# SBATCH --mem=180G
#SBATCH --partition=batch
#SBATCH --job-name=enstrophy
#SBATCH --time=00:40:00
#SBATCH --output=enstrophy.out
#SBATCH --error=enstrophy.out
# SBATCH --dependency=afterok:1598477

module purge
module load python/3.7.3 texlive

python3 ./analysis/enstrophy.py