#!/bin/bash

#SBATCH --ntasks=4
#SBATCH --nodes=1
#SBATCH --partition=amd
#SBATCH --job-name=analysis
#SBATCH --time=00:10:00
#SBATCH --output=analysis/heavy_analysis.out
# SBATCH --dependency=afterok:1597923

module purge
module load python/3.7.3 texlive

python ./analysis/save_np_binary.py